/**
 * The public surface of `artifacts/`.
 *
 * Panels get refs, reads, and the result type. They do not get `client.ts` or
 * `url.ts`: a panel that could call `fetch` itself, or build an address by
 * hand, is a panel that can be wrong about the six states in its own private
 * way, which is the situation this layer exists to end.
 */
export {
  artifactKey,
  isAlignmentTimelineArtifactKey,
  operationSequenceWorker,
  operationsSeqRef,
  readKey,
  sequenceKey,
  sequenceReadKey,
  catalogRef,
  sweepAnalysisRef,
  alignmentDescriptorRef,
  alignmentIterationReportRef,
  alignmentIterationSeriesRef,
  alignmentTimelineIndexRef,
  alignmentWorkloadSeriesRef,
  alignmentE2eSeriesRef,
  alignmentBreakdownRef,
  alignmentTimelineIterationRef,
  alignmentSequenceRef,
  predictionCasesRef,
  predictionCostTreeRef,
  predictionDescriptorRef,
  predictionKernelThroughputAnalysisRef,
  predictionOptimalityKernelLadderRef,
  predictionOptimalityWaterfallRef,
  kernelTimeShareRef,
  kernelInputDistributionRef,
  hardwareGpuRef,
  kernelMeasurementDescriptorRef,
  kernelMeasurementSummaryRef,
  kernelProfileCurveRef,
  kernelProfileDescriptorRef,
  kernelThroughputAnalysisRef,
  batchCompositionRef,
  batchSeriesRef,
  runThroughputRef,
  throughputSeriesRef,
  conservationRef,
  runOptimalityRef,
  iterationOptimalityKernelLadderRef,
  iterationOptimalityWaterfallRef,
  kvOccupancyRef,
  kvOccupancySeriesRef,
  requestStateRef,
  requestStateSeriesRef,
  runLatencyRef,
  runConcurrencyRef,
  runDescriptorRef,
  runModelRef,
  runWorkloadRef,
  runSummaryRef,
  topologyRef,
  utilizationRef,
  utilizationSeriesRef,
  workerKernelTimeShareRef,
  workerCostTreeRef,
  type ArtifactRef,
  type ArtifactValue,
  type OperationSequenceAt,
  type OperationSequenceRequest,
  type OperationsSeqRef,
  type ReadRef,
  type SeqRef,
} from './ref';
export type {
  CatalogEntry,
  CatalogRef,
  CatalogStatus,
  SweepAnalysisRef,
  AlignmentDescriptorRef,
  AlignmentIterationReportRef,
  AlignmentIterationSeriesRef,
  AlignmentTimelineIndexRef,
  AlignmentWorkloadSeriesRef,
  AlignmentE2eSeriesRef,
  AlignmentBreakdownRef,
  AlignmentTimelineIterationRef,
  AlignmentSequenceRef,
  PredictionCase,
  PredictionCasePage,
  PredictionCasesRef,
  PredictionCostTreeDetail,
  PredictionCostTreeRef,
  PredictionDescriptor,
  PredictionDescriptorRef,
  PredictionKernelThroughputAnalysis,
  PredictionKernelThroughputAnalysisRef,
  PredictionOperationSummary,
  PredictionOperationRef,
  PredictionOptimalityKernelLadderRef,
  PredictionOptimalityWaterfallRef,
  KernelComposition,
  KernelBackendSelection,
  KernelInputDistribution,
  KernelInputDistributionRef,
  HardwareGpuRef,
  KernelMeasurementDescriptorRef,
  KernelMeasurementSummaryRef,
  KernelProfileCurveRef,
  KernelProfileDescriptorRef,
  KernelThroughputAnalysis,
  KernelThroughputAnalysisRef,
  KernelThroughputPoint,
  KernelInputPoint,
  KernelInputPosition,
  KernelInputProjection,
  KernelPosition,
  KernelSampling,
  KernelSegment,
  KernelTimeShare,
  KernelTimeShareRef,
  BatchCompositionRef,
  BatchSeriesRef,
  BatchTimeline,
  BatchTimelineMetricKey,
  BatchTimelineScope,
  BatchTimelineSeries,
  BatchMetric,
  BatchScope,
  KvOccupancyRef,
  KvOccupancySeriesRef,
  KvOccupancyTimeline,
  KvTimelineBand,
  KvPeak,
  KvProjection,
  KvReservation,
  KvSeries,
  LatencyMarkers,
  LatencySeries,
  PoolKernelComposition,
  ModelParameterCounts,
  OperationRef,
  OperationSummary,
  RequestPopulation,
  RequestStatePool,
  RequestStateRef,
  RequestStateSeriesRef,
  RequestStateTimeline,
  RequestStateTimelineCategory,
  RequestStateTimelinePool,
  RequestStateTimelineWorker,
  RequestStateWorker,
  RunRequestState,
  RunLatency,
  RunLatencyRef,
  RunConcurrency,
  RunConcurrencyRef,
  RunDescriptor,
  RunDescriptorRef,
  RunResultRef,
  ArtifactCapability,
  ArtifactProvenance,
  ArtifactView,
  ArtifactViews,
  Deployment,
  DescriptorSubjectName,
  DetailArtifact,
  LifecycleStageStatus,
  ReadySubjectArtifact,
  SubjectArtifact,
  TraceDownload,
  TraceResource,
  RunBatchComposition,
  ConservationCheck,
  ConservationRef,
  RunOptimalityRef,
  ConservationStatus,
  RunConservation,
  RunThroughput,
  RunThroughputRef,
  ThroughputSeriesRef,
  ThroughputTimeline,
  ThroughputTimelineSeries,
  ThroughputTimelineView,
  ThroughputRate,
  ThroughputSegment,
  RunKvOccupancy,
  RunModel,
  RunModelRef,
  RunWorkload,
  RunWorkloadRef,
  RunSummary,
  RunSummaryRef,
  RunTopology,
  RunUtilization,
  TopologyGroup,
  TopologyPool,
  TopologyRef,
  TopologyWorker,
  UtilizationPool,
  UtilizationRef,
  UtilizationSeriesRef,
  UtilizationTimeline,
  UtilizationWorker,
  WorkerCoordinate,
  WorkerOperationBatchRole,
  WorkerOperationBuffer,
  WorkerOperationKind,
  WorkerOperationSeekResult,
  WorkerKernelComposition,
  WorkerKernelIndexEntry,
  WorkerKernelTimeShareRef,
  WorkerCostTreeDetail,
  WorkerCostTreeGroupInput,
  WorkerCostTreeInput,
  WorkerCostTreeRef,
  JsonValue,
} from './ref';
export type {
  SweepAnalysis,
  SweepCoordinateValue,
  SweepMetric,
  SweepPrimitive,
  SweepRun,
} from './schema/sweep';
export { OPTIMALITY_EPSILON_GPU_S } from './schema/optimality';
export type {
  OptimalityIterationWaterfallData,
  Optimality,
  OptimalityDecodeResult,
  OptimalityKernelLadderData,
  OptimalityKernelLadderKernel,
  OptimalityKernelRungs,
  OptimalityLevel,
  OptimalityMode,
} from './schema/optimality';
export type {
  AlignmentBreakdown,
  AlignmentDescriptor,
  AlignmentE2eSeries,
  AlignmentIterationReport,
  AlignmentIterationSeries,
  AlignmentSequence,
  AlignmentSubjectName,
  AlignmentTimelineIndex,
  AlignmentTimelineIteration,
  AlignmentWorkloadSeries,
} from './schema/alignmentTypes';
export { CostTreeValidationError, invalidCostTree, parseRawCostNode } from './schema/costTree';
export type {
  CostNode,
  CostTree,
  ExactLeafStats,
  LeafNode,
  MaxNode,
  NodeKind,
  RawCostNode,
  RawLeafNode,
  RawMaxNode,
  RawScaleNode,
  RawSlot,
  RawSumNode,
  ScaleNode,
  Slot,
  SumNode,
} from './schema/costTree';
export { isPending, isReady, type ArtifactResult } from './result';
export { readArtifact, useArtifact, useArtifacts, useArtifactWithRetry } from './read';
export {
  createOperationViewportState,
  fetchSequence,
  moveOperationViewport,
  OPERATION_BUFFER_SIZE,
  OPERATION_VIEWPORT_SIZE,
  rejectOperationBufferRequest,
  resolveOperationBufferRequest,
  shiftOperationViewport,
  useSequenceWindow,
  type OperationBufferDirection,
  type OperationBufferRequest,
  type OperationSequenceValue,
  type OperationSequenceWindow,
  type OperationViewportState,
  type OperationViewportTransition,
  type SequenceWindowController,
  type SequenceWindowRequest,
} from './sequence';
export { mergeCatalogs } from './schema/catalog';
export { modelNumber } from './schema/runModel';
